# Generated by Django 6.0.4 on 2026-04-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='slug',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
